/*
 * Generated by src/saveVersion.sh
 */
@HadoopVersionAnnotation(version="0.18.2-dev", revision="", 
                         user="tcondie", date="Thu Mar 26 11:47:06 PDT 2009", url="")
package org.apache.hadoop;
