/*
* Copyright (c) 2003 Intel Corporation
* All rights reserved.
*
*/

#include "../p2_python.h"

#include "aggregate.h"
#include "aggwrap.h"
#include "csvparser.h"
#include "ddemux.h"
#include "delete.h"
#include "demux.h"
#include "discard.h"
#include "dupElim.h"
#include "duplicateConservative.h"
#include "duplicate.h"
#include "filter.h"
#include "functorSource.h"
#include "hexdump.h"
#include "insert.h"
#include "joiner.h"
#include "logger.h"
#include "../../elements/marshal.h"
#include "marshalField.h"
#include "mux.h"
#include "noNull.h"
#include "noNullField.h"
#include "pelScan.h"
#include "pelTransform.h"
#include "ping.h"
#include "pong.h"
#include "print.h"
#include "printTime.h"
#include "printWatch.h"
#include "queue.h"
#include "randomPushSource.h"
#include "roundRobin.h"
#include "scan.h"
#include "slot.h"
#include "strToSockaddr.h"
#include "timedPullPush.h"
#include "timedPullSink.h"
#include "timedPushSource.h"
#include "timestampSource.h"
#include "tupleSource.h"
#include "unboxField.h"
#include "unmarshal.h"
#include "unmarshalField.h"

BOOST_PYTHON_MODULE(elements)
{
  #include "element.cpp"
  #include "aggregate.cpp"
  #include "aggwrap.cpp"
  #include "csvparser.cpp"
  #include "ddemux.cpp"
  #include "delete.cpp"
  #include "demux.cpp"
  #include "discard.cpp"
  #include "dupElim.cpp"
  #include "duplicateConservative.cpp"
  #include "duplicate.cpp"
  #include "filter.cpp"
  #include "functorSource.cpp"
  #include "hexdump.cpp"
  #include "insert.cpp"
  #include "joiner.cpp"
  #include "logger.cpp"
  #include "marshal.cpp"
  #include "marshalField.cpp"
  #include "mux.cpp"
  #include "noNull.cpp"
  #include "noNullField.cpp"
  #include "pelScan.cpp"
  #include "pelTransform.cpp"
  #include "ping.cpp"
  #include "pong.cpp"
  #include "print.cpp"
  #include "printTime.cpp"
  #include "printWatch.cpp"
  #include "queue.cpp"
  #include "randomPushSource.cpp"
  #include "roundRobin.cpp"
  #include "scan.cpp"
  #include "slot.cpp"
  #include "strToSockaddr.cpp"
  #include "timedPullPush.cpp"
  #include "timedPullSink.cpp"
  #include "timedPushSource.cpp"
  #include "timestampSource.cpp"
  #include "tupleSource.cpp"
  #include "unboxField.cpp"
  #include "unmarshal.cpp"
  #include "unmarshalField.cpp"
}
